MYSQL_HOST="localhost"
MYSQL_USER="root"
#MYSQL_PASSWORD="hch13579"
MYSQL_PASSWORD="123456"
MYSQL_DB="heart_echo"

UPLOAD_FOLDER="uploads"
RESULT_FOLDER="results"

SECRET_KEY="HeartEchoSystem_JWT_Secret_Key_2024_32Bytes_Long"

#nnUNet双模型配置
#2CH数据集
NNUNET_DATASET_2CH="Dataset500_Heart2CH"
#4CH数据集
NNUNET_DATASET_4CH="Dataset501_Heart4CH"

#nnUNet通用配置
NNUNET_CONFIGURATION="2d"
NNUNET_FOLD="0"

